# Generated by Django 3.2 on 2021-04-14 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subspecies', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('sow_month', models.PositiveSmallIntegerField()),
                ('plant_month', models.PositiveSmallIntegerField()),
                ('harvest_month', models.PositiveSmallIntegerField()),
                ('sunlight', models.CharField(max_length=50)),
                ('soil_acidity', models.CharField(max_length=50)),
                ('watering_frequency', models.PositiveSmallIntegerField()),
                ('fertilizing_frequency', models.PositiveSmallIntegerField()),
                ('fertilizer_type', models.CharField(max_length=50)),
                ('germination_temperature', models.PositiveSmallIntegerField()),
                ('image', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('difficulty', models.PositiveSmallIntegerField()),
                ('verified_by_admin', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
