# Generated by Django 3.2 on 2021-04-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='difficulty',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='fertilizer_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='plants',
            name='fertilizing_frequency',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='germination_temperature',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='harvest_month',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='image',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='plants',
            name='plant_month',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='soil_acidity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='plants',
            name='sow_month',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='subspecies',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='plants',
            name='sunlight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='plants',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='plants',
            name='watering_frequency',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
