# Generated by Django 3.2 on 2021-04-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_plants',
            field=models.ManyToManyField(related_name='plants', to='plants.Plants'),
        ),
    ]
